default: &default
  adapter: postgresql
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: inner-hero-api-development

test:
  <<: *default
  database: inner-hero-api-test

production:
  <<: *default
